format = """
[](#A71C1C)\
$os\
$username\
[](bg:#f95819  fg:#A71C1C)\
$directory\
[](fg:#f95819 bg:#7a0546)\
$git_branch\
$git_status\
[](fg:#7a0546)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bold bg:#A71C1C"
style_root = "bold bg:#A71C1C"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bold bg:#A71C1C"
symbol = ""
format = "[ $symbol ]($style)"
disabled = true # Disabled by default

[directory]
style = "bold bg:#f95819"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bold bg:#f95819"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bold bg:#f95819"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bold bg:#f95819"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bold bg:#f95819"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bold bg:#7a0546"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bold bg:#7a0546"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bold bg:#f95819"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bold bg:#f95819"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bold bg:#f95819"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bold bg:#f95819"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bold bg:#f95819"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bold bg:#f95819"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bold bg:#f95819"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bold bg:#f95819"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bold bg:#FFEA00"
format = '[ $time ]($style)'
